[advisories]
version = 2
yanked = "deny"
unmaintained = "warn"
ignore = []

[licenses]
version = 2
allow = [
  "Apache-2.0",
  "MIT",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unicode-DFS-2016",
  "CC0-1.0",
  "MPL-2.0",
]
allow-osi-fsf-free = "either"
confidence-threshold = 0.93
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = []
skip = []
skip-tree = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-git = []
